<?php

function shift_cipher_menu() {
    $items['shift_cipher'] = array(
        'title' => 'Shift Cipher',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('shift_cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['shift_cipher_success_page'] = array(
        'title' => 'Your cipher:',
        'page callback' => array('shift_cipher_success'),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function shift_cipher_form() {
    $form['shift_value'] = array(
        '#title' => 'Shift Value',
        '#type' => 'textfield',
        '#description' => 'Enter the number of places to shift each letter over',
        '#element_validate' => array('element_validate_integer'),
        '#required' => TRUE,
    );
    $form['shift_direction'] = array(
        '#title' => 'Shift Direction',
        '#type' => 'textfield',
        '#description' => 'Enter the direction to shift each letter over. "Left" or "Right"',
        '#required' => TRUE,
    );
    $form['user_input'] = array(
        '#title' => 'Input phrase',
        '#type' => 'textfield',
        '#description' => 'Enter the phrase to be encrypted.  Only letters, spaces, and punctuation are allowed',
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encrypt',
    );

    return $form;
}

function shift_cipher_form_validate($form, &$form_state) {
    $shift_value = $form_state['values']['shift_value'];
    $shift_direction = strtolower($form_state['values']['shift_direction']);
    $user_input = $form_state['values']['user_input'];

    if ($shift_value < 0) {
        form_set_error('', 'Shift value must be a positive integer.');
    }

    if (($shift_direction != 'left') && ($shift_direction != 'right')) {
        form_set_error('', 'Shift direction must be "left" or "right".');
    }

    if (preg_match('/[^a-zA-Z\s.,?!":;_&]/', $user_input)) {
        form_set_error('', 'Input phrase may only contain letters, spaces, and punctuation');
    }

}

function shift_cipher_form_submit($form, &$form_state) {
    $form_state['redirect'] = 'shift_cipher_success_page';
}

function shift_cipher_success() {
    return "Hooray we did it";
}
